_attn_implementation_autoset:
    value: true
_name_or_path:
    value: google/gemma-3-27b-it
_wandb:
    value:
        cli_version: 0.19.10
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": 'profiling/Time taken: GemmaGRPOTrainer._get_per_token_logps'
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": 'profiling/Time taken: GemmaGRPOTrainer.snomed_sctid_reward'
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
            "3":
                - 7
                - 13
                - 19
                - 23
                - 55
                - 66
            "4": 3.13.11
            "5": 0.19.10
            "6": 4.51.3
            "8":
                - 5
            "9":
                "1": transformers_trainer
            "12": 0.19.10
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - Gemma3ForConditionalGeneration
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: false
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
beta:
    value: 0.04
bf16:
    value: true
bf16_full_eval:
    value: false
bits:
    value: 16
boi_token_index:
    value: 255999
bos_token_id:
    value: null
cache_dir:
    value: null
cache_implementation:
    value: null
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 64
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: scripts/zero3.json
disable_dropout:
    value: false
disable_flash_attn2:
    value: true
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
double_quant:
    value: true
ds3_gather_for_generation:
    value: true
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eoi_token_index:
    value: 256000
eos_token_id:
    value:
        - 1
        - 106
epsilon:
    value: 0.2
epsilon_high:
    value: null
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
freeze_llm:
    value: false
freeze_projector:
    value: true
freeze_vision_tower:
    value: true
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value:
        use_reentrant: true
greater_is_better:
    value: null
group_by_length:
    value: false
half_precision_backend:
    value: auto
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
image_token_index:
    value: 262144
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 1e-05
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_completions:
    value: false
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: output/snomed_prediction_grpo/runs/Jan21_15-02-36_6592097332fb
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 1
logging_strategy:
    value: steps
lora_alpha:
    value: 16
lora_bias:
    value: none
lora_dropout:
    value: 0.05
lora_enable:
    value: false
lora_namespan_exclude:
    value:
        - multi_modal_projector
        - vision_tower
        - multi_modal_projector
lora_rank:
    value: 64
lora_weight_path:
    value: ""
loss_type:
    value: grpo
lr_scheduler_type:
    value: cosine
mask_truncated_completions:
    value: false
max_completion_length:
    value: 256
max_grad_norm:
    value: 1
max_length:
    value: 20
max_prompt_length:
    value: 256
max_steps:
    value: -1
metric_for_best_model:
    value: null
min_length:
    value: 0
min_p:
    value: null
mm_tokens_per_image:
    value: 256
model/num_parameters:
    value: 0
model_init_kwargs:
    value: null
model_type:
    value: gemma3
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_completions_to_print:
    value: null
num_generations:
    value: 4
num_iterations:
    value: 1
num_lora_modules:
    value: -1
num_return_sequences:
    value: 1
num_train_epochs:
    value: 5
optim:
    value: adamw_bnb_8bit
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: output/snomed_prediction_grpo
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 96
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
projector_lr:
    value: 1e-05
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
quant_type:
    value: nf4
ray_scope:
    value: last
ref_model_mixup_alpha:
    value: 0.6
ref_model_sync_steps:
    value: 512
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
reward_weights:
    value: null
run_name:
    value: output/snomed_prediction_grpo
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 100
save_strategy:
    value: steps
save_total_limit:
    value: 10
scale_rewards:
    value: true
seed:
    value: 42
sep_token_id:
    value: null
shuffle_dataset:
    value: true
skip_memory_metrics:
    value: true
suppress_tokens:
    value: null
sync_ref_model:
    value: false
task_specific_params:
    value: null
temperature:
    value: 0.9
text_config:
    value:
        _attn_implementation_autoset: false
        _name_or_path: ""
        add_cross_attention: false
        architectures: null
        attention_bias: false
        attention_dropout: 0
        attn_logit_softcapping: null
        bad_words_ids: null
        begin_suppress_tokens: null
        bos_token_id: 2
        cache_implementation: hybrid
        chunk_size_feed_forward: 0
        cross_attention_hidden_size: null
        decoder_start_token_id: null
        diversity_penalty: 0
        do_sample: false
        early_stopping: false
        encoder_no_repeat_ngram_size: 0
        eos_token_id: 1
        exponential_decay_length_penalty: null
        final_logit_softcapping: null
        finetuning_task: null
        forced_bos_token_id: null
        forced_eos_token_id: null
        head_dim: 128
        hidden_activation: gelu_pytorch_tanh
        hidden_size: 5376
        id2label:
            "0": LABEL_0
            "1": LABEL_1
        initializer_range: 0.02
        intermediate_size: 21504
        is_decoder: false
        is_encoder_decoder: false
        label2id:
            LABEL_0: 0
            LABEL_1: 1
        length_penalty: 1
        max_length: 20
        max_position_embeddings: 131072
        min_length: 0
        model_type: gemma3_text
        no_repeat_ngram_size: 0
        num_attention_heads: 32
        num_beam_groups: 1
        num_beams: 1
        num_hidden_layers: 62
        num_key_value_heads: 16
        num_return_sequences: 1
        output_attentions: false
        output_hidden_states: false
        output_scores: false
        pad_token_id: 0
        prefix: null
        problem_type: null
        query_pre_attn_scalar: 168
        remove_invalid_values: false
        repetition_penalty: 1
        return_dict: true
        return_dict_in_generate: false
        rms_norm_eps: 1e-06
        rope_local_base_freq: 10000
        rope_scaling:
            factor: 8
            rope_type: linear
        rope_theta: 1e+06
        sep_token_id: null
        sliding_window: 1024
        sliding_window_pattern: 6
        suppress_tokens: null
        task_specific_params: null
        temperature: 1
        tf_legacy_loss: false
        tie_encoder_decoder: false
        tie_word_embeddings: true
        tokenizer_class: null
        top_k: 50
        top_p: 1
        torch_dtype: bfloat16
        torchscript: false
        typical_p: 1
        use_bfloat16: false
        use_cache: true
        vocab_size: 262208
tf_legacy_loss:
    value: false
tf32:
    value: true
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: bfloat16
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tp_size:
    value: 0
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.51.3
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_dora:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_liger_loss:
    value: false
use_mps_device:
    value: false
use_vllm:
    value: false
vision_config:
    value:
        _attn_implementation_autoset: false
        _name_or_path: ""
        add_cross_attention: false
        architectures: null
        attention_dropout: 0
        bad_words_ids: null
        begin_suppress_tokens: null
        bos_token_id: null
        chunk_size_feed_forward: 0
        cross_attention_hidden_size: null
        decoder_start_token_id: null
        diversity_penalty: 0
        do_sample: false
        early_stopping: false
        encoder_no_repeat_ngram_size: 0
        eos_token_id: null
        exponential_decay_length_penalty: null
        finetuning_task: null
        forced_bos_token_id: null
        forced_eos_token_id: null
        hidden_act: gelu_pytorch_tanh
        hidden_size: 1152
        id2label:
            "0": LABEL_0
            "1": LABEL_1
        image_size: 896
        intermediate_size: 4304
        is_decoder: false
        is_encoder_decoder: false
        label2id:
            LABEL_0: 0
            LABEL_1: 1
        layer_norm_eps: 1e-06
        length_penalty: 1
        max_length: 20
        min_length: 0
        model_type: siglip_vision_model
        no_repeat_ngram_size: 0
        num_attention_heads: 16
        num_beam_groups: 1
        num_beams: 1
        num_channels: 3
        num_hidden_layers: 27
        num_return_sequences: 1
        output_attentions: false
        output_hidden_states: false
        output_scores: false
        pad_token_id: null
        patch_size: 14
        prefix: null
        problem_type: null
        remove_invalid_values: false
        repetition_penalty: 1
        return_dict: true
        return_dict_in_generate: false
        sep_token_id: null
        suppress_tokens: null
        task_specific_params: null
        temperature: 1
        tf_legacy_loss: false
        tie_encoder_decoder: false
        tie_word_embeddings: true
        tokenizer_class: null
        top_k: 50
        top_p: 1
        torch_dtype: bfloat16
        torchscript: false
        typical_p: 1
        use_bfloat16: false
        vision_use_head: false
vision_lora:
    value: false
vision_lr:
    value: 2e-06
vllm_device:
    value: null
vllm_dtype:
    value: null
vllm_enable_prefix_caching:
    value: null
vllm_gpu_memory_utilization:
    value: null
vllm_guided_decoding_regex:
    value: null
vllm_max_model_len:
    value: null
vllm_server_host:
    value: 0.0.0.0
vllm_server_port:
    value: 8000
vllm_server_timeout:
    value: 240
wandb_log_unique_prompts:
    value: false
warmup_ratio:
    value: 0.03
warmup_steps:
    value: 0
weight_decay:
    value: 0.1
